Areas/Admin/Controllers/SpecializationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MedicalAppointment.Data;
using MedicalAppointment.Models;
using Microsoft.AspNetCore.Authorization;

namespace MedicalAppointment.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class SpecializationController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SpecializationController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/Specialization
        public async Task<IActionResult> Index()
        {
              return _context.Specializations != null ? 
                          View(await _context.Specializations.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Specializations'  is null.");
        }

        // GET: Admin/Specialization/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Specializations == null)
            {
                return NotFound();
            }

            var specialization = await _context.Specializations
                .FirstOrDefaultAsync(m => m.Id == id);
            if (specialization == null)
            {
                return NotFound();
            }

            return View(specialization);
        }

        // GET: Admin/Specialization/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Specialization/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Price")] Specialization specialization)
        {
            if (ModelState.IsValid)
            {
                _context.Add(specialization);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(specialization);
        }

        // GET: Admin/Specialization/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Specializations == null)
            {
                return NotFound();
            }

            var specialization = await _context.Specializations.FindAsync(id);
            if (specialization == null)
            {
                return NotFound();
            }
            return View(specialization);
        }

        // POST: Admin/Specialization/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Name,Description,Price")] Specialization specialization)
        {
            if (id != specialization.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(specialization);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SpecializationExists(specialization.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(specialization);
        }

        // GET: Admin/Specialization/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Specializations == null)
            {
                return NotFound();
            }

            var specialization = await _context.Specializations
                .FirstOrDefaultAsync(m => m.Id == id);
            if (specialization == null)
            {
                return NotFound();
            }

            return View(specialization);
        }

        // POST: Admin/Specialization/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Specializations == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Specializations'  is null.");
            }
            var specialization = await _context.Specializations.FindAsync(id);
            if (specialization != null)
            {
                _context.Specializations.Remove(specialization);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SpecializationExists(string id)
        {
          return (_context.Specializations?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/RegistrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using MedicalAppointment.Data;
using MedicalAppointment.Models;
using MedicalAppointment.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace MedicalAppointment.Controllers
{

    public class RegistrationController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public RegistrationController(ApplicationDbContext context , UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.FindByNameAsync(User.Identity?.Name ?? "");
            if (user == null)
            {
                return NotFound();
            }
            var appointment = await _context.Appointments.Include(m =>m.Specialization)
                .OrderByDescending(m => m.RegistrationDate)
                .FirstOrDefaultAsync(m => m.UserId == user.Id);
            if (appointment == null)
            {
                return NotFound();
            }
            //ViewData["Price"] = _context.Specializations.Where(m => m.Id == appointment.SpecializationId).ToList();
            return View(appointment);
        }
        public IActionResult Payment()
        {
            return View();
        }
        
        public async Task<IActionResult> Create()
        {
            if (User.Identity?.Name != null)
            {
                ViewData["SpecializationId"] = new SelectList(_context.Specializations, "Id", "Name");
                var user = await _userManager.FindByNameAsync(User.Identity?.Name ?? "");
                if (user == null)
                {
                    return NotFound();
                }
                var AppointmentVM = new AppointmentVM
                {
                    FullName = user.FullName,
                    DateOfBirth = user.DateOfBirth,
                    Address = user.Address,
                    PhoneNumber = user.PhoneNumber,
                    Gender = user.Gender
                };
                return View(AppointmentVM);
            }
            return Redirect("/Identity/Account/Register");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PatientID,FullName,DateOfBirth,Gender,PhoneNumber,Address,AppointmentDate,AppointmentTime,Symptom,SpecializationId")] AppointmentVM appointmentVM)
        {
            ViewData["SpecializationId"] = new SelectList(_context.Specializations, "Id", "Name");
            if (ModelState.IsValid)
            {
                //ApplicationUser appUser = new ApplicationUser();
                //appUser.Id = appointmentVM.PatientID;
                //appUser.FullName = appointmentVM.FullName;
                //appUser.DateOfBirth = appointmentVM.DateOfBirth;
                //appUser.Gender = appointmentVM.Gender;
                //appUser.Address = appointmentVM.Address;
                //appUser.PhoneNumber = appointmentVM.PhoneNumber;
                //patient.Email = appointmentVM.Email;
                //await _userManager.UpdateAsync(appUser);
                //await _context.SaveChangesAsync();
                try
                {
                    Appointment appointment = new Appointment();
                    var user = await _userManager.FindByNameAsync(User.Identity?.Name ?? "");
                    var price = await _context.Specializations.FindAsync(appointmentVM.SpecializationId);
                    if (user == null || price == null)
                    {
                        return NotFound();
                    }
                    appointment.UserId = user.Id;
                    appointment.RegistrationDate = DateTime.Now;
                    appointment.Symptom = appointmentVM.Symptom;
                    appointment.AppointmentDate = appointmentVM.AppointmentDate;
                    appointment.AppointmentTime = appointmentVM.AppointmentTime;
                    appointment.SpecializationId = appointmentVM.SpecializationId;
                    appointment.Price = price.Price;
                    _context.Appointments.Add(appointment);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    ViewData["ErrorMessager"] = "Đã xảy ra lỗi! vui lòng kiểm tra thông tin đã nhập";
                    return View(appointmentVM);
                }
            }
            ViewData["ErrorMessager"] = "(2)Đã xảy ra lỗi! vui lòng kiểm tra thông tin đã nhập";
            return View(appointmentVM);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MedicalAppointment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/calendar.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MedicalAppointment.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/fonts/font-awesome.min.css" />

</head>
<body>
    <header>
        <nav class="py-3 navbar navbar-expand-sm navbar-toggleable-sm bg-light shadow navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-info" asp-area="" asp-controller="Home" asp-action="Index"><b>Bệnh viện Online</b></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark btn dropdown-toggle" data-bs-toggle="dropdown">Dịch vụ y tế</a>
                            <ul class="dropdown-menu mt-2">
                                <li><a class="dropdown-item py-2" asp-area="" asp-controller="Registration" asp-action="Create">Đăng kí khám bệnh</a></li>
                                <li><a class="dropdown-item py-2" asp-controller="" asp-action="">Dịch vụ khác</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Chuyên khoa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doctor" asp-action="Index">Bác sĩ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Hướng dẫn</a>
                        </li>
                        
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-danger" asp-area="Admin" asp-controller="Specialization" asp-action="Index">Admin</a>
                            </li>
                        }
                        @if (User.IsInRole("Doctor"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-primary" asp-area="" asp-controller="Doctor" asp-action="Redirect">Xếp lịch</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="col-md-12 mb-5">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top mt-5">
        <div class="row p-5 text-center">
            <div class="col-md-3">
                <div class="container ">
                    <h4 class="">Chức năng</h4>
                    <a href="#">Đăng kí khám bệnh theo ngày</a>
                    <br />
                    <a href="#"> Danh sách chuyên khoa</a>
                    <br />
                    <a href="#">Danh sách bác sĩ bác sĩ</a>
                    <br />
                    <a href="#">Hướng dẫn đăng kí khám</a>
                </div>
            </div>
            <div class="col-md-3">
                <div class="container ">
                    <h4 class=""></h4>
                    <a href="#">Về bệnh viện</a>
                    <br />
                    <a href="#">Đội ngũ bác sĩ &Aacute; nhân viên y tế</a>
                    <br />
                    <a href="#">Về chuyên khoa</a>
                    <br />
                    <a href="#">Hướng dẫn đăng kí khám</a>
                </div>
            </div>
            <div class="col-md-3">
                <div class="container ">
                    <h4 class="">Chức năng</h4>
                    <a href="#">Đăng kí khám bệnh theo ngày</a>
                    <br />
                    <a href="#"> Danh sách huyên khoa</a>
                    <br />
                    <a href="#">Danh sách bác sĩ bác sĩ</a>
                    <br />
                    <a href="#">Hướng dẫn đăng kí khám</a>
                </div>
            </div>
            <div class="col-md-3">
                <div class="container text-decoration-none">
                    <h4 class="">Liên hệ</h4>
                    <a href="#">SĐT: +84 339198387</a>
                    <br />
                    <a href="#">Email: dongatdong@gmail.com</a>
                    <br />
                    <a href="#">Facebook: Đông</a>
                    <br />
                    <a href="#">Zalo: 0339831002</a>
                </div>
            </div>
            &copy; 2024 - DangKiKhamBenh - <a href="https://github.com/NgoPhuocDong">PhuocDongIT(Git)</a>
        </div>
        <div>Contact:</div>
        <div>Email: dongatdong@gmail.com</div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/ajax.js" asp-append-version="true"></script>

    @*<script src="~/js/appointment.js" asp-append-version="true"></script>
    <script src="~/js/calendar.js" asp-append-version="true"></script>*@

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>